[draft] create post modal
GTBitsOfGood/focus-ga pull request #17
Opened 2024-09-24 17:24 UTC by emilyliublair

### Description

Closes https://github.com/GTBitsOfGood/focus-ga/issues/10

### Type of change

🤕 Bug Fix
🆕 Feature
🔁 Chore/Cleanup
✨ Refactor

### How to Test

### Checklist

- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (EM) have been assigned to this PR

2024-09-28 05:10 UTC, nathangong requested changes
Frontend looks great! Had some small pieces of feedback regarding code organization

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +            }
would recommend moving the validation logic here into a separate function, setting the error and removing true/false depending on whether the validation passes or fails

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +                                    </svg> : null}
what is this svg for? if it's just for the tag background, would recommend using css styling wherever possible

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +                            </div>
can you use lucide icons instead?

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +                    <svg onClick={handleClose} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6 cursor-pointer">
use lucide icons here too

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +}
use type instead of interface here

2024-09-28 05:10 UTC, nathangong commented on src/components/CreatePostModal.tsx
> +export default function CreatePostModal( props: Props ) {
Can you make the modal scrollable on overflow? Noticing that if the height of the screen is too small some elements will appear outside of the modal background

2024-09-29 00:03 UTC, emilyliublair commented on src/components/CreatePostModal.tsx
> +                                    </svg> : null}
it's a check mark to indicate that the disability is selected in the dropdown

2024-09-29 02:02 UTC, DanielChee commented
- Dropdown button should be entirely clickable
- Description textbox should be entirely clickable
- Modal Backdrop should only close when the mouse fully clicks it

Thank you and everything else looks great UX-wise!!

2024-09-29 23:47 UTC, nathangong approved these changes

2024-09-30 00:01 UTC, merged