pagination + nonfunctional filter
GTBitsOfGood/focus-ga pull request #21
Opened 2024-10-07 03:42 UTC by emilyliublair

### Description

Closes (https://github.com/GTBitsOfGood/focus-ga/issues/18)

### Type of change

🤕 Bug Fix
🆕 Feature
🔁 Chore/Cleanup
✨ Refactor

### How to Test

### Checklist

- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (EM) have been assigned to this PR

2024-10-08 02:12 UTC, nathangong requested changes
functionality looks great overall! just some small nitpicks here and there

2024-10-08 02:12 UTC, nathangong commented on src/app/(community)/page.tsx
> +  const limit = 5;
create this as a PAGINATION_LIMIT constant in `consts.ts`. set it to 10 for now?

2024-10-08 02:12 UTC, nathangong commented on src/app/(community)/page.tsx
> +              <LoaderCircle className="animate-spin text-blue-500" size={32}/>
the color doesn't seem to be working for the loading indicator (might just be on my computer tho?), lmk if its the same on yours too

2024-10-08 02:12 UTC, nathangong commented on src/components/FilterComponent.tsx
> +          <DropdownComponent key = {index} filter={filter} />
```suggestion
          <DropdownComponent key={index} filter={filter} />
```

2024-10-08 02:12 UTC, nathangong commented on src/components/DropdownComponent.tsx
> +export default function DropdownComponent<T extends { _id: string; name: string }>(
what is this type parameterization enforcing?

2024-10-08 15:09 UTC, emilyliublair commented on src/app/(community)/page.tsx
> +              <LoaderCircle className="animate-spin text-blue-500" size={32}/>
oops didn't mean to have the color anyways

2024-10-10 00:51 UTC, nathangong approved these changes

2024-10-10 00:53 UTC, merged